export const AuthRoutes = {
    USER_LOGIN: "/login",
    USER_REGISTER: "/register",
    FORGET_PASSWORD: "/forget-password",

    ADMIN_LOGIN: "/admin/login",
}


export const AuthenticatedRoutes = {
    LANDING: "/",
    USER_DASHBOARD: "/dashboard",
    USER_DIRECT_TEAM: "/direct-team",
    USER_LEVEL_TEAM: "/level-team",
    USER_REFERRAL_INCOME: "/referral-income",
    USER_ROI_INCOME: "/roi-income",
    USER_LEVEL_INCOME: "/level-income",
    USER_DEPOSIT: "/deposit",
    USER_MAKE_INVESTMENT: "/make-investment",
    USER_INVESTMENT_HISTORY: "/investment-history",
    USER_RAISE_TICKET: "/raise-ticket",
    USER_RAISE_TICKET_HISTORY: "/raise-ticket-history",
    USER_PROFILE: "/profile",
    USER_WITHDRAWAL_REQUESTS: "/withdrawal-requests",
    USER_WITHDRAWAL_HISTORY: "/withdrawal-history",
    USER_RANK_REWARD_INCOME: "/rank-reward-income",
    USER_ACTIVATION_PACKAGES: "/activation-packages",
    USER_PAY_HELP_QUEUES: "/pay-help-queues",
    USER_GET_HELP_QUEUES: "/get-help-queues",
    USER_PIN_TRANSFER: "/pin-transfer",
    USER_PIN_TRANSFER_HISTORY: "/pin-transfer-history",


    ADMIN_DASHBOARD: "/admin/dashboard",
    ADMIN_TEAM: "/admin/team",
    ADMIN_PIN_TOPUP: "/admin/pin-topup",
    ADMIN_PIN_TOPUP_HISTORY: "/admin/topup-history",
    ADMIN_REFERRAL_INCOME: "/admin/referral-income",
    ADMIN_ROI_INCOME: "/admin/roi-income",
    ADMIN_LEVEL_INCOME: "/admin/level-income",
    ADMIN_WITHDRAWAL_REQUESTS: "/admin/withdrawal-requests",
    ADMIN_UPLOAD_PAYMENT_INFO: "/admin/upload-payment-info",
    ADMIN_DEPOSIT_HISTORY: "/admin/deposit-history",
    ADMIN_RANK_REWARD: "/admin/rank-reward",
    ADMIN_ACTIVATE_USER_PIN: "/admin/activate-user-pin",
    ADMIN_ACTIVATE_USER_PIN_HISTORY: "/admin/activate-pin-history",
    ADMIN_GH_PH_QUEUES: "/admin/gh-ph-queues",
    ADMIN_ASSIGNED_PAY_HELP_HISTORY: "/admin/assigned-pay-help-history",
    ADMIN_ASSIGNED_GET_HELP_HISTORY: "/admin/assigned-get-help-history",
    ADMIN_5PH_COMPLETION_REWARD: "/admin/5ph-users",
    ADMIN_ALL_RAISE_TICKET_LIST: "/admin/raise-ticket-list",
}